import img1 from './Black glass perfume bottle and pink ribbon -20.jpg'
import img2 from './Luxury perfume bottle -12.jpg'
import img3 from './Luxury perfume bottle -6.jpg'
import img4 from './1226.jpg'
import img5 from './purple.jpg'
import img6 from './green.jpg'

let all_product = [
    {
        id:1,
        name: "Rose",
        category:["floral","daily","man","woman"],
        image: img1,
        new_price:499,
        old_price:599,
        rating: '*****'
    },
    {
        id:2,
        name: "Lavender",
        category: ["floral","daily","man","woman"],
        image:img5,
        new_price:499,
        old_price:599,
        rating: '*****'
    },
    {
        id:3,
        name: "Lily",
        category: ["floral","daily","man","woman"],
        image:img3,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:4,
        name: "Jasmine",
        category: ["floral","daily","man","woman"],
        image:img4,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:5,
        name: "Raat ki Rani",
        category: ["floral","luxury","man","woman"],
        image:img2,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:6,
        name: "Wild Flower",
        category: ["floral","daily","man","woman"],
        image:img6,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:7,
        name: "Peach",
        category: ["fruity","sweet","daily","man","woman"],
        image:img1,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:8,
        name: "Strawberry",
        category: ["fruity","sweet","daily","man","woman"],
        image:img2,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:9,
        name: "Chrysanthemum",
        category: ["floral","luxury","man","woman"],
        image:img4,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {        
        id:10,
        name: "Vanilla",
        category: ["sweet","daily","man","woman"],
        image:img3,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:11,
        name: "Chocolate",
        category: ["sweet","daily","man","woman"],
        image:img5,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:12,
        name: "Orange",
        category: ["fruity","citrus","daily","man","woman"],
        image:img2,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:13,
        name: "Lemon Grass",
        category: ["fruity","citrus","daily","man","woman"],
        image:img6,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:14,
        name: "Red Wood",
        category: ["luxury","man","woman"],
        image:img2,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:15,
        name: "Cinnamon",
        category: ["sweet","luxury","daily","man","woman"],
        image:img2,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:16,
        name: "Chandan",
        category: ["daily","man","woman"],
        image:img1,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:17,
        name: "Wild Musk",
        category: ["luxury","daily","man","woman"],
        image:img3,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:18,
        name: "Caramel",
        category: ["sweet","luxury","daily","man","woman"],
        image:img4,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:19,
        name: "Coffee",
        category: ["sweet","daily","man","woman"],
        image:img5,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
    {
        id:20,
        name: "Orchid",
        category: ["sweet","luxury","daily","man","woman"],
        image:img6,
        new_price:499,
        old_price:599,
        rating: '*****',
    },
];

export default all_product;